# Numpy

- Stands for Numerical Python and is the Core library for numerical computations
- Provides functionalities to make multi-dimensional arrays (1D, 2D, 3D or nD arrays)


- We have lists that we can use to create multi-dimensional lists instead of using arrays to perform these tasks, so why do we need Numpy?


- The advantages of using Numpy is Memory efficient, Faster, lot of convenience and functionalties.
- Numpy is built on C language which makes it so much faster.

Numpy contains `integers` and `floating point objects` and also some `containers like Lists and Dictionaries` built-in for faster mathematical calculations


<div>
<img src="attachment:Nd%20Arrays.png" width="500"/>
</div>

In NumPy, dimensions are called **axes**. In the 2-d array above, there are two axes, having two and three elements respectively. 

In NumPy terminology, for 2-D arrays:
* ```axis = 0``` refers to the axis running vertically downwards across rows
* ```axis = 1``` refers to the axis running horizontally across columns

<img src="numpy_axes.jpg" style="width: 600px; height: 400px">

## Import Numpy Package

In [1]:
import numpy as np

### Memory comparisons of Lists and Numpy Arrays

In [10]:
li_arr = [i for i in range(100)]
np_arr = np.arange(100)

print(li_arr)
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [23]:
import sys

var1 = 100
print(sys.getsizeof(var1))  # Checking the size of one Python Variable

list1 = [10,20,30,40,50]
print(sys.getsizeof(list1)) # Checking the size of a list with some elements

28
104


In [ ]:
# Checking the memory that a list with 100 element occupies

import sys
print("Size of li_arr: " + str(sys.getsizeof(li_arr)) + "bytes")
print(sys.getsizeof(li_arr))

Size of li_arr: 904bytes
904


In [ ]:
# Checking the memory occupied by a numpy array containing 100 elements

print(np_arr.itemsize)
print(np_arr.size)
print(np_arr.itemsize * np_arr.size)

4
100
400


Now let's check for large values to see the real difference

In [25]:
li_arr1 = [i for i in range(100000)]
np_arr1 = np.arange(10000)

print(sys.getsizeof(li_arr1))
print(np_arr1.itemsize * np_arr1.size)

800984
400000


### Let's see how fast a numpy array is, compared to a list

In [26]:
#python lists
L = range(1000) #0 - 999
%timeit [i**2 for i in L]

313 µs ± 17.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [27]:
a = np.arange(1000)
%timeit a**2

1.95 µs ± 166 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## 1. Creating Numpy Arrays

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```, as done above
* Initialise arrays of fixed size (when the size is known) 

### <font color='maroon'>1.1 Manually creating numpy arrays</font>

In [28]:
import numpy as np

In [36]:
list1 = [10,20,30,40,50,60,70,80]

arr1 = np.array(list1)
arr2=np.array(list1)
arr1+arr2

array([ 20,  40,  60,  80, 100, 120, 140, 160])

In [37]:
type(arr1)

numpy.ndarray

In [38]:
tuple1 = (10,20,30,40,50,60,70)

np.array(tuple1)

array([10, 20, 30, 40, 50, 60, 70])

In [39]:
#Creating an array from a list
lst = [1,2,3,4]
arr_list = np.array(lst)

In [40]:
arr1 = np.array([10,20,30,40,50])
arr1

array([10, 20, 30, 40, 50])

In [41]:
# Creating an array from a Tuple
tup = (1,2,3,4)
np.array(tup)

array([1, 2, 3, 4])

In [42]:
# Pass tuple directly to create a numpy array
arr_tup = np.array((1,2,3,4))
arr_tup

array([1, 2, 3, 4])

In [43]:
#Print Dimension of array 'arr_list'

arr_list.ndim

1

In [44]:
# Print Shape of array 'arr_list'

arr_list.shape

(4,)

**<font color='blue'>Creating a 2-D Array</font>**

In [50]:
# Creating a 2-D Array

arr_2d = np.array([[1,2,3,4], [4,5,6,7],[8,9,10,11]]) # Lists within a List
arr_2d

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
print(arr_2d.ndim)

2


In [52]:
print(arr_2d.shape) # (rows,columns)

(3, 4)


**<font color='darkblue'> 1D Array is called Vector, 2D Array is called Matrix, nD Array is called Tensor </font>**

### <font color='maroon'>1.2  Creating arrays using functions</font>

The other common way is to initialise arrays using built-in functions. 

The following ways are commonly used:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.random.random()```: Create array of random numbers
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length
* ```np.diag()```: Constructs a diagonal array

In [53]:
np.arange(1000, 5, -5, dtype = 'float')

array([1000.,  995.,  990.,  985.,  980.,  975.,  970.,  965.,  960.,
        955.,  950.,  945.,  940.,  935.,  930.,  925.,  920.,  915.,
        910.,  905.,  900.,  895.,  890.,  885.,  880.,  875.,  870.,
        865.,  860.,  855.,  850.,  845.,  840.,  835.,  830.,  825.,
        820.,  815.,  810.,  805.,  800.,  795.,  790.,  785.,  780.,
        775.,  770.,  765.,  760.,  755.,  750.,  745.,  740.,  735.,
        730.,  725.,  720.,  715.,  710.,  705.,  700.,  695.,  690.,
        685.,  680.,  675.,  670.,  665.,  660.,  655.,  650.,  645.,
        640.,  635.,  630.,  625.,  620.,  615.,  610.,  605.,  600.,
        595.,  590.,  585.,  580.,  575.,  570.,  565.,  560.,  555.,
        550.,  545.,  540.,  535.,  530.,  525.,  520.,  515.,  510.,
        505.,  500.,  495.,  490.,  485.,  480.,  475.,  470.,  465.,
        460.,  455.,  450.,  445.,  440.,  435.,  430.,  425.,  420.,
        415.,  410.,  405.,  400.,  395.,  390.,  385.,  380.,  375.,
        370.,  365.,

In [54]:
np.zeros((5,6), dtype = 'int')

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [55]:
np.ones((4,6), dtype = 'int')

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [56]:
np.full((5,5), 20)

array([[20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

In [57]:
np.diag([20,30,40,50,60, 65])

array([[20,  0,  0,  0,  0,  0],
       [ 0, 30,  0,  0,  0,  0],
       [ 0,  0, 40,  0,  0,  0],
       [ 0,  0,  0, 50,  0,  0],
       [ 0,  0,  0,  0, 60,  0],
       [ 0,  0,  0,  0,  0, 65]])

In [58]:
np.random.random((5,5))

array([[0.47579014, 0.09057644, 0.09670827, 0.17151908, 0.22824776],
       [0.88670351, 0.29025385, 0.16534244, 0.38854665, 0.31861853],
       [0.99430138, 0.50065002, 0.42052886, 0.93408554, 0.18098642],
       [0.73782274, 0.34998349, 0.25771003, 0.14511405, 0.49104052],
       [0.92440515, 0.650214  , 0.3194691 , 0.83848263, 0.50812519]])

In [59]:
np.random.randint(50, 100, size = (5,5))

array([[61, 90, 73, 91, 89],
       [95, 77, 84, 94, 93],
       [90, 95, 83, 63, 58],
       [64, 56, 53, 73, 57],
       [76, 92, 86, 92, 61]])

In [61]:
#using arange function
# arange is an array-valued version of the built-in Python range function

arr1 = np.arange(15) # 0.... n-1
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [62]:
arr_step = np.arange(10,20) #start, end (exclusive), step
arr_step

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [63]:
# Create an array of linearly spaced out values in the given range

arr_lin = np.linspace(0,50,9) #start, end, number of points
arr_lin

array([ 0.  ,  6.25, 12.5 , 18.75, 25.  , 31.25, 37.5 , 43.75, 50.  ])

In [64]:
arr3 = np.ones((4,3), dtype='int')
arr3

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [65]:
arr4 = np.zeros((3,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [66]:
arr_full = np.full((5,5), 20)
arr_full

array([[20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

In [67]:
arr_eye = np.eye(5)
arr_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [68]:
#create array using diag function
arr_diag = np.diag([10,20,13,42]) #constructs a diagonal array.
arr_diag

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 13,  0],
       [ 0,  0,  0, 42]])

In [69]:
# Extract diagonal values
np.diag(arr_diag)

array([10, 20, 13, 42])

In [70]:
#Return random floats in the half-open interval [0.0, 1.0)

arr_random = np.random.random((5,4)) 
arr_random

array([[0.93414667, 0.93962458, 0.24518025, 0.4037018 ],
       [0.97420832, 0.75320003, 0.20416721, 0.91110813],
       [0.00347854, 0.69311202, 0.84531796, 0.07430903],
       [0.0799414 , 0.93265117, 0.92158896, 0.58224222],
       [0.33018071, 0.76699777, 0.06879087, 0.62773023]])

In [71]:
random_int = np.random.randint(10 ,100,size=(6,4))
random_int

array([[61, 12, 25, 87],
       [74, 74, 76, 81],
       [26, 15, 25, 92],
       [20, 67, 10, 91],
       [82, 35, 74, 34],
       [68, 61, 47, 51]])

## 2. Basic DataTypes

In [72]:
#You can explicitly specify which data-type you want:

a_float = np.arange(15, dtype='float')
a_float

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [73]:
#The default data type is float for zeros and ones function

a = np.ones((3, 3), dtype='int')

print(a)
a.dtype

[[1 1 1]
 [1 1 1]
 [1 1 1]]


dtype('int32')

In [74]:
np_zeros = np.zeros((5,5), dtype='int')
np_zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

**<font color='blue'>Some Other Datatypes in Numpy Arrays</font>**

In [75]:
d = np.array([1+2j, 2+4j])   #Complex datatype
d
#print(d.dtype)

array([1.+2.j, 2.+4.j])

In [76]:
b = np.array([True, False, True, False])  #Boolean datatype
b
#b.dtype

array([ True, False,  True, False])

In [77]:
s = np.array(['Ram', 'Robert', 'Rahim'])
s
#s.dtype

array(['Ram', 'Robert', 'Rahim'], dtype='<U6')

## <font color='maroon'>3. Indexing and Slicing</font>

### <font color='blue'>3.1 Indexing</font>

The items of an array can be accessed and assigned to the same way as other **Python sequences (e.g. lists)**

<div>
<img src="attachment:Numpy1.png" width="450"/>
</div>

In [78]:
data = np.arange(10, 91, 10).reshape(3,3)

In [79]:
data

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [80]:
data[1,1] = 15

In [82]:
data[1:3,1:3]

array([[15, 60],
       [80, 90]])

In [101]:
data[1:3,1:3]

array([[15, 60],
       [80, 90]])

In [103]:
# For multidimensional arrays, indexes are tuples of integers:
arr_diag = np.diag([1, 2, 3])
arr_diag

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [104]:
# Print the value at 2,2
print(arr_diag[2, 2])

3


In [105]:
arr_diag[2, 1] = 33 #assigning value
arr_diag

array([[ 1,  0,  0],
       [ 0,  2,  0],
       [ 0, 33,  3]])

### <font color='blue'>3.2 Slicing</font>

In [106]:
#we can also combine assignment and slicing:

arr_sl = np.arange(10)
arr_sl

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
arr_sl[:7] = 15
arr_sl[7:] = 16
arr_sl

array([15, 15, 15, 15, 15, 15, 15, 16, 16, 16])

In [108]:
arr_new = np.arange(1,10).reshape(3,3)
arr_new

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
arr2 = np.arange(1,26,3).reshape(3,3)
arr2

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [114]:
arr2[0:2,1:]

array([[ 4,  7],
       [13, 16]])

In [115]:
arr2[1:, 1:] 

array([[13, 16],
       [22, 25]])

## <font color='maroon'>4. Numpy Numerical Operations</font>

### <font color='blue'>Basic Operations</font>

In [116]:
scalar = np.array([1, 2, 3, 4])
scalar + 12.5

array([13.5, 14.5, 15.5, 16.5])

All Arithmetic Operations happen Element-wise

In [117]:
arr_ones = np.ones(5) * 4
arr_ones

array([4., 4., 4., 4., 4.])

In [118]:
# Array Multiplications
arr1 = np.arange(1,10,1).reshape(3,3)
arr2 = np.arange(10,19,1).reshape(3,3)

In [119]:
print(arr1 * arr2) # Multiply the elements of both matrices

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [120]:
arr1.dot(arr2) # Matrix multiplication 

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

### <font color='blue'>Comparisons</font>

In [121]:
# Element-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 3, 2, 4])

np.equal(a,c)

array([ True, False, False,  True])

In [122]:
# Array-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.array_equal(a,c)

True

#### Array Mathematics

In [123]:
list1 = [12,13,14,15,13,19,20]

list1 * 2

[12, 13, 14, 15, 13, 19, 20, 12, 13, 14, 15, 13, 19, 20]

In [124]:
arr1 = np.array(list1)

In [125]:
arr1 * 2

array([24, 26, 28, 30, 26, 38, 40])

In [126]:
arr1 = np.arange(10,91,10).reshape(3,3)
arr2 = np.arange(20,101,10).reshape(3,3)

In [127]:
arr1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [128]:
arr2

array([[ 20,  30,  40],
       [ 50,  60,  70],
       [ 80,  90, 100]])

In [129]:
arr1 * arr2

array([[ 200,  600, 1200],
       [2000, 3000, 4200],
       [5600, 7200, 9000]])

In [130]:
np.multiply(arr1, arr2)

array([[ 200,  600, 1200],
       [2000, 3000, 4200],
       [5600, 7200, 9000]])

In [131]:
arr1 + arr2

array([[ 30,  50,  70],
       [ 90, 110, 130],
       [150, 170, 190]])

In [132]:
np.add(arr1, arr2)

array([[ 30,  50,  70],
       [ 90, 110, 130],
       [150, 170, 190]])

In [133]:
arr1 + 10

array([[ 20,  30,  40],
       [ 50,  60,  70],
       [ 80,  90, 100]])

In [134]:
arr1 - arr2

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [135]:
np.subtract(arr1, arr2)

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [136]:
arr1/5

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [137]:
np.divide(arr1, 5)

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [140]:
np.add(arr1,arr2)

array([[ 30,  50,  70],
       [ 90, 110, 130],
       [150, 170, 190]])

In [141]:
np.subtract(arr1,arr2)

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [142]:
np.multiply(arr1, arr2)

array([[ 200,  600, 1200],
       [2000, 3000, 4200],
       [5600, 7200, 9000]])

In [143]:
np.divide(arr1, arr2)

array([[0.5       , 0.66666667, 0.75      ],
       [0.8       , 0.83333333, 0.85714286],
       [0.875     , 0.88888889, 0.9       ]])

In [144]:
np.exp(arr1) # e**20

array([[2.20264658e+04, 4.85165195e+08, 1.06864746e+13],
       [2.35385267e+17, 5.18470553e+21, 1.14200739e+26],
       [2.51543867e+30, 5.54062238e+34, 1.22040329e+39]])

**Calculating Min, Mean, Median**

In [145]:
data = np.random.randint(10,50, size = (10,8))

In [147]:
data

array([[27, 25, 44, 44, 43, 35, 39, 19],
       [39, 10, 45, 19, 40, 12, 30, 25],
       [41, 45, 35, 28, 24, 35, 31, 28],
       [44, 37, 20, 35, 31, 48, 44, 27],
       [35, 38, 27, 35, 32, 39, 42, 37],
       [12, 28, 48, 24, 18, 14, 40, 28],
       [30, 40, 24, 23, 15, 14, 49, 13],
       [23, 39, 40, 42, 42, 33, 36, 31],
       [27, 45, 21, 42, 12, 30, 15, 10],
       [17, 41, 18, 41, 35, 22, 13, 19]])

In [148]:
np.mean(data[:2])

31.0

In [149]:
np.mean(data, axis = 0)

array([29.5, 34.8, 32.2, 33.3, 29.2, 28.2, 33.9, 23.7])

In [150]:
np.min(data, axis = 0)

array([12, 10, 18, 19, 12, 12, 13, 10])

In [ ]:
np.max(data, axis = 0)

array([39, 40, 48, 49, 39, 41, 46, 48])

In [ ]:
np.sort(data, axis = 0)

array([[14, 12, 21, 10, 13, 10, 11, 12],
       [16, 16, 25, 20, 16, 12, 22, 12],
       [18, 17, 28, 26, 17, 23, 28, 13],
       [25, 21, 31, 29, 18, 25, 28, 14],
       [27, 22, 32, 30, 23, 25, 30, 16],
       [29, 27, 34, 31, 24, 31, 31, 16],
       [31, 29, 36, 42, 25, 33, 43, 24],
       [34, 32, 47, 46, 27, 39, 43, 28],
       [35, 35, 47, 47, 28, 41, 44, 39],
       [39, 40, 48, 49, 39, 41, 46, 48]])

In [ ]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(10,19).reshape(3,3)

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4, 6])
c = np.array([1, 2, 3, 4])

In [ ]:
a.mean()

In [ ]:
np.median(b)

In [ ]:
np.min(c)

In [ ]:
np.max(a)

In [ ]:
np.mean(arr_1, axis=1)

### <font color='maroon'>Array Manipulation</font>

We have some ways to manipulate the arrays, these are - 

- numpy.concatenate(a,b)
- numpy.vstack(a,b)
- numpy.hstack(a,b)
- numpy.column_stack()
- numpy.hsplit()

Let's see one by one how they work

![Screenshot%202022-05-27%20000206.png](attachment:Screenshot%202022-05-27%20000206.png)

![Screenshot%202022-05-27%20000234.png](attachment:Screenshot%202022-05-27%20000234.png)

In [151]:
import numpy as np

In [152]:
arr1 = np.arange(25).reshape(5,5)
arr2 = np.arange(25).reshape(5,5)

In [153]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [154]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [157]:
new_array = np.hstack((arr1, arr2))
new_array

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 20, 21, 22, 23, 24]])

In [ ]:
np.vstack((arr1, arr2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
np.concatenate((arr1, arr2), axis = 1)

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 20, 21, 22, 23, 24]])

In [ ]:
big_array = np.arange(108).reshape(12, 9)

In [ ]:
big_array

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26],
       [ 27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49,  50,  51,  52,  53],
       [ 54,  55,  56,  57,  58,  59,  60,  61,  62],
       [ 63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107]])

In [ ]:
np.hsplit(big_array, 3)

[array([[  0,   1,   2],
        [  9,  10,  11],
        [ 18,  19,  20],
        [ 27,  28,  29],
        [ 36,  37,  38],
        [ 45,  46,  47],
        [ 54,  55,  56],
        [ 63,  64,  65],
        [ 72,  73,  74],
        [ 81,  82,  83],
        [ 90,  91,  92],
        [ 99, 100, 101]]),
 array([[  3,   4,   5],
        [ 12,  13,  14],
        [ 21,  22,  23],
        [ 30,  31,  32],
        [ 39,  40,  41],
        [ 48,  49,  50],
        [ 57,  58,  59],
        [ 66,  67,  68],
        [ 75,  76,  77],
        [ 84,  85,  86],
        [ 93,  94,  95],
        [102, 103, 104]]),
 array([[  6,   7,   8],
        [ 15,  16,  17],
        [ 24,  25,  26],
        [ 33,  34,  35],
        [ 42,  43,  44],
        [ 51,  52,  53],
        [ 60,  61,  62],
        [ 69,  70,  71],
        [ 78,  79,  80],
        [ 87,  88,  89],
        [ 96,  97,  98],
        [105, 106, 107]])]

In [ ]:
arr11

array([[  5,   6,   7,   8,   9],
       [ 15,  16,  17,  18,  19],
       [ 25,  26,  27,  28,  29],
       [ 35,  36,  37,  38,  39],
       [ 45,  46,  47,  48,  49],
       [ 55,  56,  57,  58,  59],
       [ 65,  66,  67,  68,  69],
       [ 75,  76,  77,  78,  79],
       [ 85,  86,  87,  88,  89],
       [ 95,  96,  97,  98,  99],
       [105, 106, 107, 108, 109],
       [115, 116, 117, 118, 119]])

In [ ]:
arr13, arr14 = np.vsplit(big_array, 2)

In [ ]:
arr13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [ ]:
arr_3 = np.array([10,20,30])
arr_4 = np.array([50,60,70])

In [ ]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(10,19).reshape(3,3)

In [ ]:
np.concatenate((arr1, arr2), axis=0)

In [ ]:
np.hstack((arr1, arr2))

In [ ]:
np.vstack((arr1, arr2))

In [ ]:
np.column_stack((arr1, arr_1))

In [ ]:
arr_new = np.arange(20).reshape(5,4)

In [ ]:
np.vsplit(arr_new, 5)

In [ ]:
np.hsplit(arr_new, 5)

### <font color='maroon'>Array Shape Manipulation</font>

**<font color='blue'>Reshaping</font>**

Reshape method does not change the shape of original array but returns a new array of the desired shape

In [158]:
arr15 = np.arange(24).reshape(3,4,2)
arr15

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [159]:
import numpy as np
b = np.array([1, 2, 3, 4, 5, 6]).reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [160]:
b.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [161]:
b.ravel()

array([1, 2, 3, 4, 5, 6])

In [162]:
b.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

#### Reshaping to 3D array

In [163]:
arr_new = np.arange(24).reshape(4,3,2)

In [164]:
arr_new

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [165]:
arr_new.ndim

3

## Sorting

In [168]:
arr_1d = np.array([9,3,11,4,1,15])

In [169]:
np.argsort(arr_1d)

array([4, 1, 3, 0, 2, 5], dtype=int64)

## Read Data from text file

## Broadcasting

Basic operations on numpy arrays (addition, etc.) are elementwise

This works on arrays of the same size. Nevertheless, It’s also possible to do operations on arrays of different sizes if NumPy can transform these arrays so that they all have the same size: this conversion is called broadcasting.

The image below gives an example of broadcasting:

In [173]:
arr11 = np.arange(12).reshape(4,3)
arr12 = np.arange(9).reshape(3,3)

In [174]:
arr11 * arr12

ValueError: operands could not be broadcast together with shapes (4,3) (3,3) 

![numpy_broadcasting.png](attachment:numpy_broadcasting.png)

In [ ]:
a = np.tile(np.arange(0, 40, 10), (3,1))
print(a)

print("*************")
a=a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
*************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [ ]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [ ]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
a_1d = np.arange(0, 40, 10)
a_1d.shape

(4,)

In [ ]:
a_2d = a_1d[:, np.newaxis]  # adds a new axis -> 2D array
a_2d.shape

(4, 1)

In [ ]:
a_2d

array([[ 0],
       [10],
       [20],
       [30]])

In [ ]:
b

array([0, 1, 2])

In [ ]:
a_2d + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])